---
title: "Data Story"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=TRUE,eval=TRUE}
library(tidyverse)
homicide <- read.csv("database2.csv")
head(homicide)
homicide
```

### Which rows and columns of the dataset will be used to answer this question?
Year, Perpetrator Age, Relationship, Weapon, Sex

```{r}
new <- homicide %>%
 filter(Year == 2014 & Perpetrator.Sex != "Unknown" & Relationship != "Unknown" & Weapon != "Unknown" & Weapon != "Drowning" & Weapon != "Fall" & Perpetrator.Age != 0) %>%
 select(Year, Perpetrator.Age, Relationship, Weapon, Perpetrator.Sex)

new
```

```{r}
unique(new$Relationship)
unique(new$Weapon)
unique(new$Perpetrator.Age)
```

```{r}
newdf <- new %>%
  mutate(RelationshipNew = case_when(
    Relationship == "Mother" ~ "Family",
    Relationship == "Father" ~ "Family",
    Relationship == "Family" ~ "Family",
    Relationship == "Wife" ~ "Family",
    Relationship == "Daughter" ~ "Family",
    Relationship == "Son" ~ "Family",
    Relationship == "Husband" ~ "Family",
    Relationship == "In-Law" ~ "Family",
    Relationship == "Sister" ~ "Family",
    Relationship == "Brother" ~ "Family",
    Relationship == "Stepdaughter" ~ "FamilyAfter",
    Relationship == "Stepson" ~ "FamilyAfter",
    Relationship == "Stepfather" ~ "FamilyAfter",
    Relationship == "Girlfriend" ~ "VeryClose",
    Relationship == "Boyfriend" ~ "VeryClose",
    Relationship == "Boyfriend/Girlfriend" ~ "VeryClose",
    Relationship == "Friend" ~ "VeryClose",
    Relationship == "Ex-Wife" ~ "MarriageBefore",
    Relationship == "Ex-Husband" ~ "MarriageBefore",
    Relationship == "Acquaintance" ~ "Acquaintance",
    Relationship == "Employer" ~ "Acquaintance",
    Relationship == "Employee" ~ "Acquaintance",
    Relationship == "Neighbor" ~ "Acquaintance",
    Relationship == "Stranger" ~ "Stranger",
    Relationship == "Common-Law Wife" ~ "CommonLaw",
    Relationship == "Common-Law Husband" ~ "CommonLaw",
  ))
summary(newdf)
```

```{r}
hello <- newdf %>% filter(RelationshipNew == "Acquaintance") %>% select(RelationshipNew, Weapon)
hello
```

```{r}
library(ggplot2)
bar_width <- 1
ggplot(data = hello, aes(x = Weapon)) +
  geom_bar(width = bar_width)

```

```{r}
ggplot(data = newdf, aes(x = RelationshipNew, 
                      fill = Weapon)) +
  geom_bar(position = "fill") + labs(x = "Relationship between victim and murders", y = "Proportion", title = "Relationship between " )
```
```{r}
ggplot(, aes(x = Perpetrator.Age, fill = Weapon)) + geom_histogram(binwidth = 30, alpha = 0.6) +
labs(x = "Loan amount ($)",y = "Frequency",title = "Age vs. Weapon Use during homicide") + facet_wrap(~ Weapon, nrow = 2)

```

**Sex**
```{r}
summer <- newdf %>% filter(Perpetrator.Sex == "Male") %>% select (Perpetrator.Sex, Weapon)
summer 
bar_width <- 1
ggplot(data = summer, aes(y = Weapon)) +
  geom_bar(width = bar_width)
```

```{r}
winter <- newdf %>% filter(Perpetrator.Sex == "Female") %>% select (Perpetrator.Sex, Weapon)
winter 
bar_width <- 1
ggplot(data = winter, aes(y = Weapon)) +
  geom_bar(width = bar_width)
```

```{r}
ggplot(as, aes(x = Perpetrator.Sex, y = Weapon)) + 
 geom_point()
```

```{r}
ggplot(data = newdf, aes(x = Perpetrator.Sex, 
                      fill = Weapon)) +
  geom_bar(position = "fill") + labs(x = "sex of perpetrators", y = "Proportion", title = "Relationship between " ) + facet_wrap(~ Weapon, nrow = 3)

```
**Age**
```{r}
as <- newdf %>% arrange(Perpetrator.Age) 
as
```

```{r}
ggplot(as, aes(x = Perpetrator.Age, y = Weapon)) + 
 geom_point()
```

```{r}
ggplot(as, aes(x = Perpetrator.Age, fill = Weapon)) + geom_histogram(binwidth = 45, alpha = 0.6) +
labs(x = "Perpetrator Age",y = "Weapon use",title = "Amounts of Lending Club loans") 
```

```{r}
ggplot(as, aes(x = Perpetrator.Age, fill = Weapon)) + geom_histogram(binwidth = 30, alpha = 0.6) +
labs(x = "Loan amount ($)",y = "Frequency",title = "Age vs. Weapon Use during homicide") + facet_wrap(~ Weapon, nrow = 2)
```

```{r}
ggplot(as, aes(x = Perpetrator.Age)) + geom_density()
ggplot(as, aes(x = RelationshipNew)) + geom_density()
ggplot(as, aes(x = Weapon)) + geom_density()
```

```{r}
ggplot(as, aes(x = RelationshipNew, fill = Weapon)) +
geom_density(adjust = 1, alpha = 0.5)
```

